version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: cars
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1999
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  postgres_data: